package com.david.facetec;

import android.app.Activity;
import android.util.Log;
import android.widget.Toast;

import androidx.annotation.NonNull;

import com.david.Processors.Config;
import com.david.Processors.Processor;
import com.david.Processors.ThemeHelpers;
import com.facetec.sdk.FaceTecSDK;

import java.util.HashMap;

import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;

public class FacetecPlugin implements MethodChannel.MethodCallHandler {

    private final static String TAG = "FacetecPlugin";
    private final Activity activity;
    private FacetecManager facetecManager;
    private boolean isInit = false;
    private MethodChannel.Result result;
    public static MethodChannel flutterChannel;

    public FacetecPlugin(Activity activity) {
        this.activity = activity;
    }

    public static void registerWith(Activity activity, BinaryMessenger messenger) {
        flutterChannel = new MethodChannel(messenger, "com.nexosxt.plugin/facetec");
        FacetecPlugin instance = new FacetecPlugin(activity);
        flutterChannel.setMethodCallHandler(instance);
    }

    @Override
    public void onMethodCall(@NonNull MethodCall call, @NonNull MethodChannel.Result result) {
        this.result = result;
        switch (call.method) {
            case "initService":
                Log.v(TAG, "========init called!");
                String userId = call.arguments.toString();
                Log.v(TAG, "UserId received!: " + userId);
//                ZoomGlobalState.userId = "nexosgo_user_" + randomUUID();
                // Initialize FaceTec SDK
                Config.initializeFaceTecSDKFromAutogeneratedConfig(activity, new FaceTecSDK.InitializeCallback() {
                    @Override
                    public void onCompletion(final boolean successful) {
                        if (successful) {
                            ThemeHelpers.setAppTheme("Pseudo-Fullscreen");
                            Log.e(TAG, "===============init success");
                        } else {
                            Log.e(TAG, "===============init fail");
                        }
                    }
                });
                // Set the FaceTec Customization defined in the Config File.
                FaceTecSDK.setCustomization(Config.currentCustomization);
                break;
            case "livenessCheck":
                if (isInit)
                    getFacetecManager().livenessCheck(sessionTokenErrorCallback);
                else Toast.makeText(activity, "init error", Toast.LENGTH_SHORT).show();
                break;
            case "enrollUser":
                if (isInit)
                    getFacetecManager().enrollUser(sessionTokenErrorCallback);
                else Toast.makeText(activity, "init error", Toast.LENGTH_SHORT).show();
                break;
            case "authenticateUser":
                if (isInit) {
                    getFacetecManager().authenticateUser(sessionTokenErrorCallback);
                } else Toast.makeText(activity, "init error", Toast.LENGTH_SHORT).show();
                break;
            case "photoIDMatch":
                if (isInit)
                    getFacetecManager().photoIDMatch(sessionTokenErrorCallback);
                else Toast.makeText(activity, "init error", Toast.LENGTH_SHORT).show();
                break;
            default:
                activity.runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        result.notImplemented();
                    }
                });

        }
    }

    private FacetecManager getFacetecManager() {
        if (facetecManager == null) {
            if (activity != null && !activity.isFinishing()) {
                facetecManager = new FacetecManager(activity);
            }
        }
        return facetecManager;
    }

    interface SessionTokenCallback {
        void onSessionTokenReceived(String sessionToken);
    }

    // Handle error retrieving the Session Token from the server
    Processor.SessionTokenErrorCallback sessionTokenErrorCallback = new Processor.SessionTokenErrorCallback() {
        @Override
        public void onError(String method, HashMap error) {
            activity.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    flutterChannel.invokeMethod(method, error);
                }
            });
        }

        @Override
        public void onSuccess(String method, HashMap message) {
            activity.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    flutterChannel.invokeMethod(method, message);
                }
            });
        }
    };
}
